/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class FibonacciEvenSum {
    public static void main(String[] args) {
        int f1 = 1;
        int f2 = 2;
        int fn = 0;
        int total = 0;
        while (f2 < 4_000_000) {
            fn = f1 + f2;
            f1 = f2;
            f2 = fn;
            if (f1 % 2 == 0) {
                total += f1;
            }
        }
        System.out.println(total);
    }
}
